# ===== Veely - Production application.yml =====

spring:
  application:
    name: veely

  # --- Datasource: SOLO via variabili d'ambiente ---
  datasource:
    url: ${SPRING_DATASOURCE_URL}          # es: jdbc:mysql://localhost:3306/veely?useSSL=false&serverTimezone=Europe/Rome
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  mail:
    host: smtps.aruba.it
    port: 465
    username: risorseumane@sincolsrl.it
    password: Risorsesin2025@@
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.debug: true  # <-- AGGIUNTO PER DEBUG
      mail.smtp.connectiontimeout: 15000
      mail.smtp.timeout: 15000
      mail.smtp.writetimeout: 15000

  # --- JPA / Hibernate ---
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update                   # in prod: valida lo schema (niente create/update)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC                   # coerenza temporale

  # --- Flyway migrations ---
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true              # utile se parti da schema esistente

  # --- Upload ---
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

server:
  port: 8080
  forward-headers-strategy: native         # dietro Nginx/Reverse Proxy
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true
        same-site: strict

# --- Log ---
logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: INFO

# --- Actuator (minimo indispensabile) ---
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true

# --- Storage upload (path assoluto, sovrascrivibile via ENV) ---
veely:
  storage:
    root: ${VEELY_STORAGE_ROOT:/opt/veely/uploads}
